### ISSUE TITLE
rengex 프로그램 문의 드립니다

### ISSUE THREAD

**Issue by Brothers3398** [nanikit/Rengex#2]
안녕하세요
문의드릴대가 마땅히 못찾겟어서 여기가 맞나 모르겟네요
rengex만들어주신거 잘쓰고잇습니다

그런데 어느순간부터 그룹 2개이상을 작업을 못하고잇습니다
사실 며칠전까지는 전혀 변경없이 잘됫는데...안됩니다
파일이 커서그런가? 싶기도 해서 19년도 버전을쓰다가
그래서 21년도 테스트버전으로 몇번 잘되더니 같은 증상이 발생햇습니다
![문의](https://user-images.githubusercontent.com/119965811/205990968-97fbd288-4ce1-458f-bf95-a602b269a1dd.JPG)

정확하게는 캡쳐 그룹 3개에서 3개를 전부다 이상없이 번역해주다가 어느순간부터 그룹 1개만 작업이됩니다
소량이면 2개까지는 되긴합니다만 원래 문장txt파일은 19메가정도 되는 사이즈고요
원래 문장파일 번역시키면 진행도가 약 600만개 넘어가던걸로 기억하는데
-meta파일이 겹쳐셔 그런가 하고 지워서 잘되던때 파일은 없습니다
저상태가 되니까 그룹1번만 번역이되서 150만정도밖에 나오지 않습니다

![image](https://user-images.githubusercontent.com/119965811/205992546-65148dbf-c44b-41e2-bf30-216dd353e1bf.png)

그래서 몇몇 문장구문만 따로 뺴서 돌려봣는데 1번그룹(name) 전부 3번그룹(trans) 일부만 진행되고 적용이 되지않습니다
https://regex101.com/r/lKp1H2/1
해당 문장구문 regex101에 저장해둔 파일입니다

[rengex결과물.zip](https://github.com/nanikit/Rengex/files/10169220/rengex.zip)
그리고 이건 제가 rengex로 직접 돌린 결과물폴더들입니다
1번 name은 Jap을 캡처해서 replace에서 Kor로 변경시키는 일을 합니다
2번 files는 파일명들을 따로 뽑아내서 번역하고 replace에서 작업을 한번 거칩니다(ez트랜스 번역후 한자 병기표현삭제등)
3번그룹 trans는 문장들이라  번역하려고 그룹작업한거고요
처음부터 안됫으면 내가 정규식을 잘못짯나하겟는데
잘되다가 갑자기 안됩니다....

수정
![image](https://user-images.githubusercontent.com/119965811/205997168-c22ed356-a85f-4334-8275-7e391b39322a.png)
-------
실행파일 다른하드에 옮기고 나서 돌려보니까 되네요.. 어음...;
-------
번역 완료하고 나서 체크해보니 일부 누락되어잇어서 다시 하니까 또 안되네요

**Comment by Brothers3398** [comment]
원인을 찾은거같습니다
중간의 postive lookbehind기능을빼면 돌아는 가내요
그렇다고 중간의 식을 임시로 수정해서 lookaround를
제거하니까
Meta에서 찾지못하고 name/trans 그룹만 동작하네요
Trans에 도 룩어라운드 수식이잇는데..음
아무튼 2번 file쪽이 문제네요
https://regex101.com/r/lKp1H2/3
===오후7시 30분 수정
집에서 좀더 확인해본결과 예전에 잘됫었던것기록을 백업해둔게 있어서 찾아보니까
^과 $에서 버그가 발생하는거 같습니다.

**Comment by nanikit** [comment]
으아… 노티가 왜 풀려있었는지 모르겠네요. 해결하셨다니 다행이에요.

lookbehind 그룹을 썼을 때 catastrophic backtracking이라는 현상이 발생할 수 있어요. 정규식 매칭이 너무 오래 걸리는 현상인데 그게 맞다면 정규식을 최적화해줘야 해요.

올려주신 링크는 제가 의미를 다 모르겠어서 혹시 해결해야할 버그가 남아있는 것 같으면 코멘트 달아주세요.
