### ISSUE TITLE
2줄이상 되는 매칭에서 repla 치환기능이 비정상 동작하는데 확인 부탁드립니다+질문이 있습니다

### ISSUE THREAD

**Issue by Brothers3398** [nanikit/Rengex#3]
안녕하세요
번역작업하고잇는데 의문이 있어서 문의드립니다
https://regex101.com/r/3Xy74q/2
해당 링크 보시면 정규식은 저렇게 해서 여러줄이상으로 어느 문장 나올떄까지 번역시키게 해놧구요
`.match`
`(?<=<ICS[ ]レシピ>)(?<recipetext>[^<生成数]*)`
repla치환기능을 의도는 처음에 이렇게 했습니다 
`.repla`
`(?:)[ ](?=.*?\0recipetext$)`
`\uFFA0`
그런데 의도한대로 되지않아서
`[ ]`
`\uFFA0`
로 테스트 해보니까 되더라고요(물론 전체적으로 되버려서 이러면 안됩니다)
그래서 테스트용으로
`(?<recipetext>튼튼한[ ]옷감:)`
로 match를 바꾸고 다시 맨처음에 한 걸로 해보니까
이상없이 의도한대로 되더군요
repla (?:)기능은 2줄이상이면 적용이 안되는건가요?
원래 의도한 기능은 
튼튼한 옷감: 1을 기준으로할떄
튼튼한(유니코드공백)옷감:(반각공백)1로 하려고 하엿습니다
:1 이부분은 .tran_번역.txt 에서 고쳐주려고 했었구요
안된다면 아마 한줄씩 해야될꺼같은데..한줄로 하게되면 다른 스크립트에서 쓰는 내용이 걸려버려서 그렇습니다
혹시 정규식 범위안의 문장을 논캡쳐 그룹으로 잡은다음 거기서만 따로 캡처그룹으로 매칭시키는 방법이 잇나요?
예를들어서

===================
<ICS カテゴリー: 調合>
<ICS レシピ>
蜂蜜酒: 4
夢見水: 2
ラベンダー: 2
</ICS レシピ>

<SGカテゴリ:料理のレシピ>
<SG説明:【黄金の鶏の餌】
材料：キャベツ: ２　トウモロコシ：２　豆：２
小麦粉：２　バター：１　夢リンゴ：１
生成数：1
満腹度：-
睡眠度：-
ステート付与：-
合成カテゴリ：調合
>

=================
이렇게 같이있을떄
<ICS カテゴリー: 調合>
<ICS レシピ>
**蜂蜜酒: 4
夢見水: 2
ラベンダー: 2**
</ICS レシピ>

<SGカテゴリ:料理のレシピ>
<SG説明:【黄金の鶏の餌】
材料：キャベツ: ２　トウモロコシ：２　豆：２
小麦粉：２　バター：１　夢リンゴ：１
生成数：1
満腹度：-
睡眠度：-
ステート付与：-
合成カテゴリ：調合
>
진하게 처리한 부분만 번역을 시켜야 합니다
예시로 든건 사실 번역해도 아무문제 없긴 합니다만 다른 스크립트 들이 번역하면 안되는 상태라서...그렇습니다
ICS 플러그인에서 쓰는
生成数:과
難易度:는 번역이되면 안되서 그렇습니다

**Comment by nanikit** [comment]
결론부터 말하자면 치환 정규식을 `(?:)[ ](?=[\s\S]*?\0recipetext$)`로 바꿔보세요.

.이 개행문자에 매칭되지 않아서 생긴 문제같아요.

`(?<recipetext>[^<生成数]*)` 이 부분은 `<`, `生`, `成`, `数`가 아닌 한 최대한 매칭하는 거라 혹시 소괄호가 필요했던 게 아닐까 생각이 들었네요.

**Comment by Brothers3398** [comment]
되네요 알려주셔서 감사합니다.
되고나서 생각해보니까 meta쪽 폴더보니까 하나로만 되어잇으니가 여러줄로 되서 처리된게 당연한건데 그걸 생각을 못했네요
애초에 자기가 2줄이상 하게 해놓고선 무슨생각을한건지..
생각이 짧았습니다
`: 2` 이부분은 반각공백으로 해야해서
한줄로 될꺼라고 생각을 하고 `(?:)[ ](?=:[ ]\d\0.*\0recipetext$)`로 하면 혹시 되지않을까?
하고 테스트해본건데 당연히 안되겟네요
그냥 노트패드++가지고 바꾸는게 더 쉬울꺼같네요
알려주셔서 감사합니다

**Comment by nanikit** [comment]
원하는 매칭이 이게 맞으실까요?
https://regex101.com/r/xJoblD/1

**Comment by Brothers3398** [comment]
> 원하는 매칭이 이게 맞으실까요? https://regex101.com/r/xJoblD/1

아 거의 비슷합니다

https://github.com/futokoro/RPGMaker/blob/master/FTKR_ItemCompositionSystem.ja.md
이게 해당 플러그인 입니다
이 플러그인이 대상에 반각공백이 들어가니까 오류가 나서그거때문에 수정중이엿습니다

원래의도한건  <ics レシピ>    </ics レシピ>안에 生成数하고
실패율? 저 부분은 번역하먼 안되서 그렇게 햇엇습니다
지정범위안에사 매칭만 하는 방법이 잇군요..알려주신거보고 좀 공부해서 해봐야겟네요

아토믹그룹은 논그룹 예기해주실때 보긴봣는데...
이해가 잘안되서그냥 넘겻는데 이렇게 보네요

그런데 rengex프로그램이 pcre? 방식이 이니리 NET(C#) 방식으로 해야맞는거엿군요
전 이제까지 Pcre로 계속 햇엇네요

알려주서셔 감사합니다

**Comment by Brothers3398** [comment]
![image](https://user-images.githubusercontent.com/119965811/212885698-f3552b86-f68e-486a-8b2d-eb3d6417e581.png)

첫줄에서부터 해석이 제대로 안되네요..
`<ICS[ ]レシピ>이후 줄부터 매칭을 시작해서`
`</ICS[ ]レシピ>이후줄부터는 매칭하지 않는다`
`0줄에서 200줄 범위안에`
이게 맞는 해석인가요?
아토믹 그룹쪽은 뭔지 모르겟습니다
아무문자나 라인피드가 나올떄까지 매칭한다 인거같은데..
아무문자나 라인피드가 나올떄까지 매칭하고 /ICS줄 이후는 매칭하지않는다 라는건가요?
아토믹 그룹은 역추적을 하지않는다 라는데 이게 이해가잘 안되네요

**Comment by nanikit** [comment]
어려운 게 맞아서 저도 이렇게까지 사용하는 건 오히려 안 좋지 않나 싶긴 해요. 주석으로 설명해볼게요.

```
(?<=<ICS[ ]レシピ>\n # 매칭하려는 문자열 앞에 <ICS ...>가 나와야 함
(?>.*               # 줄 끝까지 읽음. 아토믹 그룹을 쓰지 않으면 문자마다 다음 패턴을 매칭해 시간초과 발생.
(?<!</ICS[ ]レシピ>) # 단 읽은 줄이 </ICS...>면 안 됨
\n?                 # 개행문자 매칭
){0,200}?)          # 위와 같은 줄을 200개까지 허용. 

(?<recipetext>^[^<].*$) # <로 시작하지 않는 줄에 매칭

(?=              # 매칭하려는 문자열 뒤에
(?>.*\n)*?       # 아무 줄이나 나온 후에
</ICS[ ]レシピ>) # </ICS...>가 나와야 함
```

**Comment by Brothers3398** [comment]
주석 달아주셔도 이해하기가 많이 어렵군요
아토믹그룹은 매칭맞는지를 한번만 시도한다고 생각하면 쉬울려나..
보다보면 이해할날이 오겟죠
알려주셔서 감사합니다
