### ISSUE TITLE
rengex101에서는 매칭이 되는데 번역이 되지 않습니다

### ISSUE THREAD

**Issue by Brothers3398** [nanikit/Rengex#4]
안녕하세요

또다시 질문이 생겨서 문의드립니다
https://regex101.com/r/7YDTtu/3
일단 regex101에서 해보면 매칭은 되는데..
rengex에서 넣으면 번역이 되지않습니다

혹시 쓰면 안되는식이라도 잇는건가요?
아니면 rengex랑 적용이 달르게 되는식이라도 잇는건지..

아그리고 저번에 알려주신 덕분에 다행히 해당게임은 오류없이 잘 됫습니다 감사합니다

**Comment by nanikit** [comment]
아래로 되는지 확인해보시겠어요? regex101에서는 LF 문자만 있는 것처럼 취급하지만 윈도 파일은 CRLF일 수도 있는 것 같아요.
그리고 그 경우에 ^$나 \r\n 매칭에 주의해보시는 게 어떨까 해요.

```
(?<=\[Inst_Type:_CALC_FUNC]\r?\n^[ ]{2}\[__text__]\[◆])
(?<select>[ぁ-ゔァ-ヴー々〆〤一-龥一-龥]+)
(?=\[◆\]\r?$)
```

이번 경우에서 제가 사용한 방식은 설정파일을 수정하면서 테스트하는 거였어요. rengex는 설정 파일 변경을 실시간 감시하기 때문에 파일 변경 후에 바로 사용해도 괜찮아요.
1. 그냥 넣어볼까? 안 되네?
2. 앞뒤 lookaround 그룹을 지워볼까? 되네?
3. 뒤쪽 lookahead 그룹을 넣어볼까? 안 되네?
4. 뒤쪽 lookahead 그룹에서 \\[만 넣어볼까? 되네?
5. 뒤쪽 lookahead 그룹에서 한 글자 더 넣어볼까? 되네?
...

대충 이런 접근이었어요.

**Comment by Brothers3398** [comment]
아 /n만 되서 그런거엿군요...
Regex101에서는 잘되길래 혹시나 해서 /n을 [/r/n] 이렇게 햇엇는데 이것도 알려주신거보니까 안될만 햇엇네요
감사합니다 
집에가게되면 해보겟습니다

**Comment by Brothers3398** [comment]
집에서 확인해보니까 잘되네요
쓰는사람이 많아졋으면 서로 이런건 물어볼텐데 물어볼대가 마땅치않아서...번거롭게 해드리는거 같네요
도와주셔서 감사합니다

**Comment by nanikit** [comment]
아직 괜찮아요. 오히려 질문이 너무 없으면 개선할 생각도 안 할 것 같아요. 그리고 여기가 물어보기엔 가장 적합한 것 같네요.
애초에 제가 좀 더 편리하게 만들었어야 했는데 그러지 않은 업보일 뿐이죠.
