### ISSUE TITLE
특정 범위내에서만 매칭할떄 정규식 질문드립니다

### ISSUE THREAD

**Issue by Brothers3398** [nanikit/Rengex#5]
안녕하세요 
저번에 알려주신
https://regex101.com/r/xJoblD/2
이 정규식으로 배껴가면서 작성하고 잇습니다
보면 알려주셧던 해당 정규식은 범위내에 어디서든 매칭될려고 정상적으로 동작합니다

https://regex101.com/r/hoKsE4/3
그래서 제가 짜면서 비슷한 의도가 필요한 부분이 있어서 배끼면서 하는중인데
일단 매칭식 잡기전에 조건식부터 맞추려고 연습중인데
이 정규식은 label={ 뒷부분에서만 매칭이 가능하게 되어잇습니다
제가 어디 오타난대 없나..하고 계속 보고잇는데 잘모르겟네요
ttext={ 안쪽 label={ 앞쪽의 문장들만 매칭이 필요합니다

다르게 동작하는 이유를 혹시 알수잇을까요?

**Comment by Brothers3398** [comment]
> 
글 올리고나서 보니까 label뒤에 \t를 안넣어서그랫네요  좀더 생각해볼껄....

**Comment by nanikit** [comment]
저도 질문한 다음에 바로 보이는 경우가 왕왕 있더라고요 ㅎㅎ
