### ISSUE TITLE
non-capture group 관련해서 질문드립니다

### ISSUE THREAD

**Issue by Brothers3398** [nanikit/Rengex#6]
안녕하세요 
질문드릴게 있어서 다시 왓습니다
매칭쪽에 (?:) 으로 noncapture 그룹으로 매칭에서 예외시킬려고 했는데(사실 이게맞게 쓰는건지 모르겟습니다 초반에 만든거라)
regex101사이트에서 그렇게 동작하길래..그렇게 만들었습니다
https://regex101.com/r/aAupPf/1
해당정규식 데모입니다
![image](https://user-images.githubusercontent.com/119965811/215277339-fecf711e-dc59-4107-b458-4b1620d0dc29.png)

원래 의도한건 이런 매칭이엿습니다

![image](https://user-images.githubusercontent.com/119965811/215277155-de034bd2-d972-411d-a73d-b3f29080e317.png)

그런데 의도하지 않은 번역이 자꾸나와서 따로 편집기로 수정해주다가
시간남아서 보정해주려고 보니까 tran.txt 파일을 보니
이렇게 매칭이 되서 처리가 되더라고요
해당 기능으로 rengex에서 구현하려면 다시 lookaround 기능으로 짜서 고치긴 햇습니다

이게 안되는게 정상적인건지 잘모르겟어서 질문드립니다
저게 저렇게된게 처음짤때 lookaround 기능 잘 모르기도 했었고 Utf부분을 캡처해서 따로 repla에서 Jap-->Kor 로 바꾸는
동작을 햇엇습니다 지금은 그기능은 없에고 걍 냅둔건데 저렇게 캡처하고 있더라고요
그때는 trans.txt를보니까 저렇게 캡처를 안하고 의도한대로 하고잇었습니다

**Comment by nanikit** [comment]
Rengex의 설정 파일 동작이 바뀐 건 repla 규칙이 바뀐 적 한 번이 있어요. 이게 아니라면 프로그램 동작이 달라진 건 저도 짐작이 안 가네요.

올려주신 regex101 예시는 제가 보기엔 둘 다 정상이에요. 첫 번째를 해석하면

```
[::][Utf][000003][017772][::]○【戦闘】立ち絵表示[::]
^^^^^^^^ \[::]\[(?:Utf) 매칭

][000003][017772][::]○【戦闘】立ち絵表示[::]
^^^^^^^^^^^^^^^^^ 딱히 매칭되는 게 없어 스킵

[::]○【戦闘】立ち絵表示[::]
^^^^                        (?<=\[::])
    ^^^^^^^^^^^^^^^^^^^     ((?!.+(?:mps|png|ogg|mp3|jpg|dat|sav|wav|txt))(?<trans>.+))
                       ^^^^ (?=\[::]) 매칭
```

두 번째 예제를 해석하면

```
[::][Utf][000003][017772][::]○【戦闘】立ち絵表示[::]
^^^^                                                 (?<=\[::])
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^     ((?!.+(?:mps|png|ogg|mp3|jpg|dat|sav|wav|txt))(?<trans>.+))
                                                ^^^^ (?=\[::]) 매칭
```

의도한 게 첫 번째가 맞다면 다음처럼 할 수도 있을 것 같아요. 같은 행동을 하는 정규식이 하나만 있는 것도 아니고 제가 다 이해하지 못한 가능성이 커서 아무래도 상관없긴 해요.
https://regex101.com/r/5UwCre/1 ([v3](https://regex101.com/r/5UwCre/3))
```
(
\[::]\[Utf].*?(?=\[::])|
\[::](?=.*?\.(mps|png|ogg|mp3|jpg|dat|sav|wav|txt))(?<file>.*?)(?=\[::])|
\[::](?<text>.*)(?=\[::])|
\\cself(?<select>.+)\[::]
)
```

**Comment by Brothers3398** [comment]
> 

아 그게 두번째 예제보면 
`#\[::]\[(?:utf)` 가 아니고
`\[::]\[(?:utf)`
가 원래 정상입니다 trans.txt에서 이렇게 캡쳐된다고 보여드리려고 고친거라서..
일단 해당문제가 되는부분은 다시 새로 짜서 고치긴 했습니다

처음꺼 해석해주신대로 해당 매칭이 의도한건데 trans.txt를 보면 두번쨰 해석해주신대로 
매칭되서 논캡쳐링 그룹이`(?:utf)` 잘못동작하는거 같아서요

![image](https://user-images.githubusercontent.com/119965811/215283866-29c10791-66e3-4147-b217-7dd666b1c11b.png)

이게 예전에 쓰던 위에 문의드린 정규식으로 햇을떄 이렇게 나옵니다
일단은 논캡쳐링 그룹 쓰는건 전부 새로 수정해야 될꺼같습니다

**Comment by nanikit** [comment]
아 rengex에 넣었을 때 안 된다는 말이었군요. utf를 Utf로 고쳐야 할 것 같아요.

**Comment by Brothers3398** [comment]
> Owner

위에글 올리자마자 바로 그렇게 고쳣더니 의도한대로 되네요
(?i) 있어서 대소문자 무시하는줄알았습니다

**Comment by nanikit** [comment]
이건 고쳐야겠네요. 너무 신경을 안 쓰니 이런 오류가…

**Comment by nanikit** [comment]
새로 릴리즈했어요.

**Comment by Brothers3398** [comment]
> 새로 릴리즈했어요.

아 신경써주셔서 감사합니다
