### ISSUE TITLE
번역파일 줄 수가 부족합니다 라는 오류는 어떤오류인가요?

### ISSUE THREAD

**Issue by Brothers3398** [nanikit/Rengex#7]
![image](https://user-images.githubusercontent.com/119965811/216299864-7a2f540d-09c7-4aa3-9d67-974c9db6d7d9.png)

번역파일 줄수가 부족합니다 라는 오류가 납니다
![image](https://user-images.githubusercontent.com/119965811/216300213-0631b9db-cfb3-4b54-8709-32f385113e13.png)
원본은 대략 이정도 번역량이 필요하고요
그래서 위에 2개 오류난게 파일 2개로 짤라봣는데도 오류나더라고요
아마 번역하는 텍스트가 많아서 좀 오류가나는거같은데..
![image](https://user-images.githubusercontent.com/119965811/216300539-8e102a1a-cd93-42c0-89ee-8321e915444c.png)
추출텍스느는 이런식이라 최대한 필요없는 글자를 제거해둔 상태입니다
![image](https://user-images.githubusercontent.com/119965811/216304164-b5fd9d29-1ced-4a04-b54e-5b9ca5d72bb2.png)
새로운2는 번역작업을 성공한 상태고 약 원본에서 2만줄정도로 짜른겁니다
아래파일은 반으로 짤랏을떄의 파일이고 10만줄 조금넘습니다(원본은 19만줄-26메가)
![image](https://user-images.githubusercontent.com/119965811/216306860-fdc3d3bc-dad1-48b7-820b-4ddd722ffeb0.png)

그런데 예정에 이정도 양 되는것도 한번에 됬엇는데...무슨이유에서인지 안되는건지 잘모르겟습니다
잘됫던 파일은 32만줄 용량 21메가
![image](https://user-images.githubusercontent.com/119965811/216305373-5c2c153d-63e8-4108-b84d-f6c3ef08e36c.png)
트랜스 파일은 7메가이상인데..
용량문제가 아니라 다른게 문제인건지 잘모르게습니다

**Comment by nanikit** [comment]
이 오류는 tran파일이랑 tran_번역 파일 줄 수가 달라서 생기는 문제예요. 줄 수가 많으면 무시라도 가능한데 적으면 어떻게 매칭해야 할지 모르거든요.
아마 일부 번역문에서 줄 수가 달라지는 문제가 있을 것 같고 어쩌면 이 프로그램 버그일지도 모르겠는데 적은 용량으로 재현이 가능해야 확인해 볼 것 같아요.

**Comment by Brothers3398** [comment]
일단 이만줄식 짤랐는데 오류가나길래 만줄로 줄여봣는데
https://regex101.com/r/7YDTtu/5
이부분에서 오류가 납니다
아래쪽 test string이 해당 만줄 오류부분 전체입니다
trans쪽 보니까 추출/번역이 덜된건 아닌거 같은데 잘모르겟네요

**Comment by Brothers3398** [comment]
> 이 오류는 tran파일이랑 tran_번역 파일 줄 수가 달라서 생기는 문제예요. 줄 수가 많으면 무시라도 가능한데 적으면 어떻게 매칭해야 할지 모르거든요. 아마 일부 번역문에서 줄 수가 달라지는 문제가 있을 것 같고 어쩌면 이 프로그램 버그일지도 모르겠는데 적은 용량으로 재현이 가능해야 확인해 볼 것 같아요.

혹시 더 줄여드려야되나요?

**Comment by nanikit** [comment]
變なところだけ銳すぎだろ、コイツ。
伴藤
해당 텍스트를 아네모네로 번역해보면 번역이 잘 안 되는 걸 알 수 있어요. 이지트랜스 고유 문제라서 잘 해봐야 우회가 전부일 것 같아요. 당장은 문제 부분을 찾아서 전처리로 미리 번역하는 수가 있을 것 같아요. 많이 귀찮은 문제네요.

**Comment by Brothers3398** [comment]
> 
예전에 다른것 번역할떄 저런식으로 번역을 제대로 못하긴 햇엇는데 그래도 줄수가 맞아서 그랫나..
윈머지로보니까 줄수가 적네요..
이건 ehnd에서 어케 해야 해결될꺼같네요 답변 감사합니다

**Comment by Brothers3398** [comment]
![image](https://user-images.githubusercontent.com/119965811/216314028-d38cd5c0-41f0-4104-865e-0bee7ec02664.png)
보니까 번역에서 줄하나가 생겨버리면서 아네모네도 제대로 번역을 못하네요
![image](https://user-images.githubusercontent.com/119965811/216314813-1cd7df2f-62c1-4516-9932-f4dab4c60e18.png)

![image](https://user-images.githubusercontent.com/119965811/216314922-5ec867c0-0edb-468c-8050-7ee5d70bb9d0.png)
그런데 단문번역은 또 그냥되네요(대신 줄하나를 만들어버림)
이건 EHND문제인거같은데..

**Comment by Brothers3398** [comment]
다른 질문입니다만 저런 오류가 낫을떄 trans쪽 보고 마지막줄쯤에서 번역 오류가 났다고 생각하면 될까요?

**Comment by nanikit** [comment]
아뇨. 그런 보장은 없어요. 그냥 문제되는 문자열을 어디 넣는지에 따라 달라지는 문제니까요.
저는 이분 검색으로 문제 문자열을 찾았어요.

**Comment by Brothers3398** [comment]
> 
그렇군요..
음 다음에도 그러면 고생좀 하겟네요
알려주셔서 감사합니다

**Comment by nanikit** [comment]
https://github.com/nanikit/ehnd/releases
여기서 J2KEngine.dll을 받아서 이지트랜스 폴더에 있는 걸 교체해서 써도 될 것 같아요. 터지지만 않게 고친 버전이에요.

**Comment by Brothers3398** [comment]
> https://github.com/nanikit/ehnd/releases 여기서 J2KEngine.dll을 받아서 이지트랜스 폴더에 있는 걸 교체해서 써도 될 것 같아요. 터지지만 않게 고친 버전이에요.

아 이건 제가 전처리필터에 터지는 한자들만 골라서 따로 만들어서 해결하긴했습니다
그래도 한번 써봐야겟네요 다른거에서 또 터질수잇으니까
감사합니다
