### ISSUE TITLE
아주 가끔 ehnd 필터를 rengex가 반영을 못합니다

### ISSUE THREAD

**Issue by Brothers3398** [nanikit/Rengex#8]
![image](https://user-images.githubusercontent.com/119965811/216802714-acbf443a-7170-4770-bac6-26604b34e60c.png)
이건 사용자 사전이 반영 된거고요(전처리/후처리필터포함)

![image](https://user-images.githubusercontent.com/119965811/216802727-f40b1b35-aea4-497a-8443-e60703fdd63a.png)
이건 사용자 사전이 반영 안된사항입니다

![image](https://user-images.githubusercontent.com/119965811/216803280-f2937b7a-5c11-4ffc-86a7-4012a2ccd09b.png)
이게 필터 반영되서 처리된 정상문장입니다

아주 가끔 이런 현상이 발생하던데..
이게 match.txt를 여러번 수정햇거나-아주가끔
아네모네를 킨상태에서 번역했다거나-항상그럼
(근데 이건 만드신 eztrans server통해서 쓰는거면 아네모네가 이미 쓰고잇어서 안되는걸로 생각해서 버그는 아닌거 같습니다)
할떄 그러더라고요
아네모네켯을떄는 제가볼떄는 버그가 아닌거 같고
정말 아주가끔 match를 여러번 수정햇을떄 나오는데 이럴떈 rengex를 그냥 껏다가 다시 실행하면 이상이없긴합니다
다시 여러번 match를 여러번 수정을해도 안나올떄도 잇고요
요번에 작업하다가 마침 나와서 보고드립니다

두번쨰로 사소한겁니다만

repla에서 주석을 달떄
`(?:)\?(?=\0.+?\0text$)   #23-01-26(문장끝부분에 ?이후 #이름시 오류나는것 수정)`
`？`
이런식으로달면
저 #23-01-26수정 부분떄문에 오류가 발생하더군요 치환을 제대로 못합니다
이건 사소한거라 그냥 윗줄로 넣고 끝냇는데 (match.txt쪽에 설명되어잇기도하고)
`(?<livemakertrans>.+)(?=\[◆]\[_DEF) #문장`
`|#선택지(2023-01-25) `
`(?<=\[Inst_Type:_CALC_FUNC]\r?\n^[ ]{2}\[__text__]\[◆]) `
match쪽은 저렇게 중간에 넣어도 주석처리가 되서 사소한거지만 알려드립니다

**Comment by nanikit** [comment]
필터라는 게 ehnd의 전처리, 후처리 필터일까요 아니면 rengex의 치환 규칙일까요? 아마 전자라고 생각하는데 저도 가끔 본 적은 있지만 100% 발생시키는 조건을 발견하지 못해서 해결하기 힘든 부분이었어요.

저번 번역 실패는 원인이라도 알 수 있지만 이건 원인부터 알기 힘들어서 살펴보려고 해도 고칠 수 있을진 아직 모르겠어요.

두번째는 치환 파일에선 줄 끝 주석을 지원하지 않는 게 의도한 동작이긴 한데 많이 거슬릴까요? 현재 상태도 나쁘진 않다고 보는 게 치환 파일은 정규식이 여러 줄이 될 수 없어서 줄 끝 주석을 달면 오히려 읽기 힘들어질 것 같거든요.

**Comment by Brothers3398** [comment]
ehnd의 전처리 후처리 필터 예기입니다
예 가끔나와서 원인이 뭔지 잘모르겟더라고요 역시 인지하고 계신거군요
원인을 재현가능하면 그건 그떄 다시 알려드리도록 하겟습니다

그리고 두번쨰는 거슬리는건 없습니다
그냥 덤으로 이렇더라 라고 알려드린거라
사실 말씀하신대로 읽기 더 힘들어지더군요 그래서 일부러 그러셧나 보다 라고 생각하고 쓰고있었습니다
