### ISSUE TITLE
정규식에서 and 조건으로 번역을 시킬수 잇을까요?

### ISSUE THREAD

**Issue by Brothers3398** [nanikit/Rengex#9]
어..그러니까 설명하기가 좀 복잡한데
![image](https://user-images.githubusercontent.com/119965811/217028529-1f797982-224c-455e-b4aa-1219bacd5ae1.png)
이런식으로 2개가 겹치는 그룹이 잇고

![image](https://user-images.githubusercontent.com/119965811/217028595-4b218aa3-e559-41d0-9b49-da8e4c553bec.png)
이런식으로 하나만 캡쳐되는 그룹이잇습니다

이걸 2개만 겹치는 그룹만 번역시키고 싶습니다
처음에는 단순하게 생각햇는데 and 연산자 자체가 없는건지 제가 못찾는건지 안보이네요

어떻게 하다보니까
`(?=.*a)(?=.*b).*`
`aaaaaabbbbb <--매칭됨`
`aaaaa <---매칭안됨`
`bbbbb <-매칭안됨`
`aaasssssssb <-매칭됨`

까지는 찾기는 했는데 
이게 이용도는 아닌거같고 잘 모르겠습니다
적용을 제대로 못시키겟네요

https://regex101.com/r/468bvp/1

해당 정규식입니다

**Comment by nanikit** [comment]
일단 설명하신 대로면 알려주신 방법이 정답이네요. 설명만으론 가장 간단한 형태가 (a).*?(b)가 될 것 같아요. 그럴 수 없는 이유가 있을 것 같은데 설명으론 알기 힘드네요.

정규식이 원래 작성할 때 편하고 읽긴 어려워서 의도보다 원하는 입출력을 설명하는 게 더 편할 수도 있어요. 어쩌면 의도에 정확히 대응하는 고급 기능이 필요하지 않을 수도 있거든요. 가령 현재까지 만든 정규식과 매칭할 텍스트에서 어디가 매칭이 되어야 하는데 안 된다거나 매칭되지 말아야 하는데 매칭이 된다거나 하는 점을 알려주는 게 더 설명하고 이해하기 편하지 않을까 싶어요.

첫번째 캡처에서 2개가 겹치는 그룹이 있다는 부분이 잘 이해가 안 가네요. 4개 매칭 전부 다른 텍스트를 추출한 건데 어떤 부분이 겹친다는 걸까요?

**Comment by Brothers3398** [comment]
역시 설명하기가 좀 힘드네요
일단 해당에문에서 
selectlive1그룹 단독으로는 17개가 캡처가 됩니다
selectlive2그룹 만으로는 47개가 캡처가되고요
맨위 스샷을 보시면 match1과 match3이 그룹은 다른데 캡처된 글자가 같습니다
이렇게 같은 글자가 있는 부분만 번역을 하고 싶습니다

이유가 라이브메이커3 엔진이 이미지로 사용하는 버튼같은경우에는 selectlive1 그룹에 캡처가 되지않습니다
그래서 글자로 사용하는 선택지는 match1(selectlive1그룹)과 match3(selectlive2그룹)에 두개가 겹치는 것이고요
외부 테이블 끌어오는 데이타명칭이라던가 이미지 선택지 버튼명칭이 selectlive2 그룹에 캡처가 됩니다
그래서 결과물에서 and 식이 가능한지..문의드린겁니다

캡처된 내용에 대한 and 조건으로 번역이 가능한지 라고 하는게 좀더 확실하겟네요

selectlive1 그룹의 내용과 selectlive2 그룹내용중 같은게 있으면 그걸 번역
입니다

원래 초기의도는 selectlive1이랑 selectlive2 조건식이 각각 다르니까 이걸 조건식을 둘다 and처리해서 하면 한 그룹으로 
캡처가 가능할까? 라고 생각했는데 단순히 생각햇는데 
이게 아니더군요..
각각 캡처된 내용에서 겹치는부분만 번역하는게 의도입니다

**Comment by Brothers3398** [comment]
설명이 제대로 될려나  모르겟는데 캡처된 그룹들이 들어가는(순서상관없이)
데이타 테이블이 있다고 가정하고

A 데이타1
B 데이타2
C 데이타1
D 데이타4
E 데이타3
F 데이타4

라고한다면
A C D F만 번역이 되면 됩니다

**Comment by nanikit** [comment]
의도를 이해한 것 같아요. 정규식을 짜보고 있어서 답변을 못 드렸네요. 이러라고 있는 정규식은 아닌 것 같지만 또 불가능한 건 아니라서 하지 말라고 하기도 뭐하네요.
기본적으론 처음에 말했던 방식을 쓰면 될 것 같아요.

**Comment by nanikit** [comment]
https://regex101.com/r/468bvp/2 이게 원하는 정규식이 맞을까요? 보니까 _CALC_FUNC가 항상 _JUMP 앞에 나오는 것 같아서 그런 전제를 했어요.

**Comment by Brothers3398** [comment]
selectlive1기준으로 selectlive2와 겹치는곳에 selectlive1만 캡처되어서 반정도긴하지만
이걸 반대로해서 selectlive2기준으로 selectlive1에 겹치는곳에 selectlive2를 캡처시키면 되겟군요
감사합니다
그건 제가직접 한번 해보겟습니다

`^\[__LINE__:\d{8}]\[__OFFSET__:\d{8}]\[Inst_Type:_CALC_FUNC]\s{0,4}  \[__text__]\[◆]` <--매치식

`(?<image_select>.*?)`  <--그룹

`(?=\[◆\]\s{0,4}  \[__text__]\[◆]_tmp\[◆][\s\S]*?`
`^\[__LINE__:\d{8}]\[__OFFSET__:\d{8}]\[Inst_Type:_JUMP]\s{0,4}  \[__text__]\[◆]\1\[◆\]\s{0,4}`
`  \[__text__]\[◆]選擇値\[◆])`    <--lookahead식

그런데 이런식으로 나눠진거같은데 해석이 잘 안되는데 혹시 설명해주실수잇을까요?
\1은 image_select 그룹 예기인거같은데... 

image_select 그룹내용중에 매칭되는게 있으면 으로 적용이 되는건가요?

https://regex101.com/r/OLKMGF/1

이해를 이렇게했는데 이게 뭔가 아닌거같습니다

**Comment by nanikit** [comment]
매치식 부분은 _CALC_FUNC가 나오는 라인을 찾은 후에 버리는 부분이고
그룹 부분은 추출하고 변환하기 위해서 캡처한 부분이에요.
lookahead 그룹은 나중에 _JUMP 부분이 나오는지 검사하는 부분이라고 보면 돼요. 생소할 수 있는 점을 추려볼게요.
- [\s\S]를 쓰면 공백,비공백 문자 전부를 의미해서 줄 끝에서 멈추는 게 아니라 파일 끝까지 진행해요.
- \1은 말한 것처럼 여기선 image_select인 첫번째 그룹에 매칭하는 걸 의미해요, 즉 동일한 문자열이 나오는 걸 의미해요.

추가한 정규식 예제에서는 또는 조건(`|` )이 들어가서 3번째나 4번째 라인을 매칭할 때 첫번째 그룹이 빈 것으로 간주될 것 같아요.

질문이 잦은 것 같아서 혹시 디코 그룹을 만들면 더 편하실까요?

**Comment by Brothers3398** [comment]
그래주시면 저는 감사합니다만 괜히 더 귀찮게 해드리는거 아닌지 모르겟네요

**Comment by nanikit** [comment]
어렵지 않아 보여서 만들어봤어요. https://regex101.com/r/468bvp/3
디코 그룹은 만들면 알려드릴게요.

**Comment by Brothers3398** [comment]
아 직접해볼려고 햇는데 감사합니다
다음번에 이런식으로 쓸일잇을떄 참고하겟습니다

**Comment by nanikit** [comment]
[메인 페이지](https://github.com/nanikit/Rengex#readme)에 디코 링크 추가했어요.
